### PR TITLE
Support project whitelists/blacklists rendering and editing

### PR DESCRIPTION
**Pull request by jessesuen**
- Support project whitelists/blacklists rendering and editing
- Support adding/removing of project role groups
- Remove obsolete rollback result from models
- Support new style of structured application sources

### CODE REVIEW

**Comment by jessesuen** [comment]
image

**Comment by jessesuen** [comment]
image

**Comment by jessesuen** [comment]
image

**Review by alexmt — APPROVED** [review]
Looks great! Please fix linter warnings before merging:

```
yarn lint                                                                                                                                                                (docker-for-desktop/default)
yarn run v1.12.3
$ tslint -p ./src/app

ERROR: /Users/amatyushentsev/root/argo-cd-ui/src/app/applications/components/application-creation-wizard/application-creation-wizard.tsx[219, 1]: Exceeds maximum line length of 180
ERROR: /Users/amatyushentsev/root/argo-cd-ui/src/app/applications/components/applications-list/applications-list.tsx[213, 17]: Identifier 'source' is never reassigned; use 'const' instead of 'let'.
ERROR: /Users/amatyushentsev/root/argo-cd-ui/src/app/settings/components/project-edit-panel/project-edit-panel.tsx[102, 1]: Exceeds maximum line length of 180
ERROR: /Users/amatyushentsev/root/argo-cd-ui/src/app/settings/components/project-edit-panel/project-edit-panel.tsx[128, 1]: Exceeds maximum line length of 180
ERROR: /Users/amatyushentsev/root/argo-cd-ui/src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx[9, 1]: Import sources within a group must be alphabetized.
ERROR: /Users/amatyushentsev/root/argo-cd-ui/src/app/shared/models.ts[161, 1]: space indentation expected
ERROR: /Users/amatyushentsev/root/argo-cd-ui/src/app/shared/models.ts[162, 1]: space indentation expected
ERROR: /Users/amatyushentsev/root/argo-cd-ui/src/app/shared/models.ts[166, 1]: space indentation expected
ERROR: /Users/amatyushentsev/root/argo-cd-ui/src/app/shared/models.ts[170, 1]: space indentation expected
```

**Pull request merged**
