### PR TITLE
Network view external nodes

### PR DESCRIPTION
**Pull request by alexmt**
Closes #357

ezgif-2-badd79a71b2b

### CODE REVIEW

**Review by alexec — COMMENTED** [review]
I find this a bit colorful and don't know what the colors mean. Are they traffic load? Lost packets?

**Comment by alexmt** [comment]
Colors are supposed to help to differentiate traffic from the different source. E.g. traffic from load balancer `a` is red all the way to the pod, traffic from `b` is green etc. 

I'm also concerned that the visualization of 10 load balancers might cause an epileptic seizure.

**Comment by alexmt** [comment]
@alexec do you think less prominent colors should help?

**Comment by alexec** [comment]
Could we use symbols instead of colors?

**Comment by alexmt** [comment]
As we discussed offline: increased line width, added color to traffic source nodes, increased number of colors in the palette.

**Pull request merged**
